apiVersion: v1
kind: Service
metadata: 
  name: bom-backend-service
  namespace: bom-processor
spec:
  selector:
    app: bom-backend
  ports: 
  - protocol: TCP 
    port: 5000
    targetPort: 5000
  type: ClusterIP 