apiVersion: v1 
kind: Service
metadata:
  name: bom-frontend-service 
  namespace: bom-processor
spec: 
  selector: 
    app: bom-frontend
  ports: 
  - Protocol: TCP 
    port: 80 
    targetPort: 80
  type: LoadBalancer 

  